# this is a clone of https://docs.haskellstack.org/en/stable/travis_ci/
# alternative: https://github.com/harendra-kumar/packcheck

sudo: false
language: generic
cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

env:
- RESOLVER=lts-10.3
- RESOLVER=lts-11.13

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --resolver=$RESOLVER --no-terminal --install-ghc test --fast --only-dependencies

script:
- export SAML2_WEB_SSO_ROOT=`pwd`
- stack --resolver=$RESOLVER --no-terminal test --fast --haddock --no-haddock-deps

notifications:  # see https://docs.travis-ci.com/user/notifications
  email: false
