resolver: lts-14.27

packages:
- .

extra-deps:
- git: https://github.com/wireapp/hsaml2
  commit: cc47da1d097b0b26595b8889e40c33c6c0c1c551    # master (Feb 27, 2020)
- git: https://github.com/wireapp/hspec-wai
  commit: ca10d13deab929f1cc3a569abea2e7fbe35fdbe3  # https://github.com/hspec/hspec-wai/pull/49
- invertible-hxt-0.1  # for hsaml2
- hedgehog-quickcheck-0.1.1

- ormolu-0.0.5.0
- ghc-lib-parser-8.10.1.20200412@sha256:b0517bb150a02957d7180f131f5b94abd2a7f58a7d1532a012e71618282339c2,8751  # for ormolu-0.0.5.0

nix:
  packages:
  - zlib
  - pkgconfig
  - libxml2
