resolver: lts-10.3

packages:
- .
- location:
    git: https://github.com/wireapp/hsaml2
    commit: d917572c09591b9fa8c8907e41ba587b8d0f70d3
  extra-dep: true
- location:
    git: https://github.com/wireapp/stack-prism
    commit: 631978447e3a1d658613f606ce7a679d7cce2294
  extra-dep: true
- location:
    git: https://github.com/wireapp/hspec-wai
    commit: ca10d13deab929f1cc3a569abea2e7fbe35fdbe3  # https://github.com/hspec/hspec-wai/pull/49
  extra-dep: true
- location:
    git: https://github.com/wireapp/servant-multipart
    commit: a5f0b9ce508f9d4c28a41d2b856387a7db281577  # https://github.com/haskell-servant/servant-multipart/pull/17
  extra-dep: true

extra-deps:
- invertible-hxt-0.1  # for hsaml2
