resolver: lts-14.12

packages:
- .

extra-deps:
- git: https://github.com/wireapp/hsaml2
  commit: e395cd1477630d6f8385c44b9010f68b8a1ede06
- git: https://github.com/wireapp/hspec-wai
  commit: ca10d13deab929f1cc3a569abea2e7fbe35fdbe3  # https://github.com/hspec/hspec-wai/pull/49
- invertible-hxt-0.1  # for hsaml2
- hedgehog-quickcheck-0.1.1

nix:
  packages:
  - zlib
  - pkgconfig
  - libxml2
