resolver: lts-11.13

packages:
- .

- location:
    git: https://github.com/wireapp/hsaml2
    commit: 4e2167cbf158e90097993a6277b50915ce2eff60
  extra-dep: true

- location:
    git: https://github.com/wireapp/hspec-wai
    commit: ca10d13deab929f1cc3a569abea2e7fbe35fdbe3  # https://github.com/hspec/hspec-wai/pull/49
  extra-dep: true

extra-deps:
- invertible-hxt-0.1  # for hsaml2
- servant-multipart-0.11.2
- yaml-0.9.0

# why on earth would these not be in stackage?!
- conduit-parse-0.2.1.0
- xml-conduit-parse-0.3.1.2
