resolver: lts-16.14

packages:
- .

extra-deps:
- git: https://github.com/wireapp/hsaml2
  commit: b652ec6e69d1647e827cbee0fa290605ac09dc63  # https://github.com/wireapp/hsaml2/pull/9 (Feb 18, 2021)
- git: https://github.com/wireapp/hspec-wai
  commit: 0a5142cd3ba48116ff059c041348b817fb7bdb25  # https://github.com/hspec/hspec-wai/pull/49
- invertible-hxt-0.1  # for hsaml2
- servant-multipart-0.11.5 # Dropped from stackage

- ormolu-0.1.4.1
- ghc-lib-parser-8.10.1.20200412@sha256:b0517bb150a02957d7180f131f5b94abd2a7f58a7d1532a012e71618282339c2,8751  # for ormolu
nix:
  packages:
  - zlib
  - pkgconfig
  - libxml2
