resolver: lts-14.12

packages:
- .

extra-deps:
- git: https://github.com/wireapp/hsaml2
  commit: cc47da1d097b0b26595b8889e40c33c6c0c1c551    # master (Feb 27, 2020)
- git: https://github.com/wireapp/hspec-wai
  commit: ca10d13deab929f1cc3a569abea2e7fbe35fdbe3  # https://github.com/hspec/hspec-wai/pull/49
- invertible-hxt-0.1  # for hsaml2
- hedgehog-quickcheck-0.1.1

- ormolu-0.0.3.1
- ghc-lib-parser-8.8.2.20200205@sha256:343f889f7b29f5ec07cf0d18d2a53f250fa5c002b6468a6a05b385d0191b8d34,8408  # for ormolu-0.0.3.1

nix:
  packages:
  - zlib
  - pkgconfig
  - libxml2
