resolver: lts-11.13

packages:
- .

# Needs to have QuickCheck bumped: see
# https://github.com/hedgehogqa/haskell-hedgehog/issues/213
- location:
    git: https://github.com/hedgehogqa/haskell-hedgehog
    commit: 7516d04673563455a55cf69eb1c490fbbb7f2a5f
  subdirs:
  - hedgehog-quickcheck
  extra-dep: true

- location:
    git: https://github.com/wireapp/hsaml2
    commit: 4548e90f34384d10e0186040492b2a652c1cb127
  extra-dep: true

- location:
    git: https://github.com/wireapp/hspec-wai
    commit: ca10d13deab929f1cc3a569abea2e7fbe35fdbe3  # https://github.com/hspec/hspec-wai/pull/49
  extra-dep: true

extra-deps:
- invertible-hxt-0.1  # for hsaml2
- servant-multipart-0.11.2
- yaml-0.9.0
